// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omtbvsybxsxqqgdottqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tdGJ2c3lieHN4cXFnZG90dHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDQ3NjEsImV4cCI6MjA2Mzg4MDc2MX0.Dwqa6A_9VBNZomkyoIctBXjSYOOZ2j2HmVUZO6ruf_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);